version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ecocollect-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/var/www
      - /var/www/vendor # Thêm dòng này để giữ lại vendor bên trong container
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/database/database.sqlite
    networks:
      - ecocollect-network

networks:
  ecocollect-network:
    driver: bridge
